sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t zavanton/react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true zavanton/react-test npm run test

after_success:
  - docker build -t zavanton/super-client -f Dockerfile .
  - echo "$HUB_PASSWORD" | docker login -u "$HUB_ID" --password-stdin
  - docker push zavanton/super-client

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: super-project
  env: Superproject-env
  bucket_name: elasticbeanstalk-us-east-2-565447122202
  bucker_path: project-super
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
